import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import localFont from 'next/font/local';

const universalSans = localFont({
  src: [
    {
      path: '/fonts/Universal-Sans-Display-300.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '/fonts/Universal-Sans-Display-350.ttf',
      weight: '350',
      style: 'normal',
    },
    {
      path: '/fonts/Universal-Sans-Display-450.ttf',
      weight: '450',
      style: 'normal',
    },
  ],
  variable: '--font-universal-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${universalSans.variable} antialiased `}>{children}</body>
    </html>
  );
}
