import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import localFont from 'next/font/local';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const universalSans = localFont({
  src: [
    {
      path: '../public/fonts/Universal-Sans-Display-300.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../public/fonts/Universal-Sans-Display-350.ttf',
      weight: '350',
      style: 'normal',
    },
    {
      path: '../public/fonts/Universal-Sans-Display-450.ttf',
      weight: '450',
      style: 'normal',
    },
  ],
  variable: '--font-universal-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={`${universalSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
